-- Your SQL goes here
create table if not exists default_products (
    id uuid primary key default uuid_generate_v4(),
    name varchar(100) not null,
    unity_types_id uuid not null references unity_types(id),
    default_categorys_id uuid not null references default_categorys(id),
    image_url varchar(255)
)

-- Manga
-- Banana
-- Arroz
-- Feijão
-- Carne
-- Frango
-- Café
-- Açúcar
-- Sal
-- Óleo
-- Leite
-- Queijo
-- Presunto
-- Pão
-- Macarrão
-- Molho de tomate
-- Farinha de trigo
-- Ovos
-- Maçã
-- Laranja
-- Cebola
-- Alho
-- Batata
-- Tomate
-- Suco
-- Refrigerante
-- Água
-- Sabonete
-- Shampoo
-- Condicionador
-- Papel higiênico
-- Detergente
-- Amaciante
-- Desinfetante
-- Alvejante
-- Limpador multiuso
-- Creme dental
-- Escova de dentes
-- Enxaguante bucal
-- Desodorante
-- Sabão em pó
-- Esponja de cozinha
-- Leite condensado
-- Creme de leite
-- Gelatina
-- Chá
-- Vinagre
-- Mostarda
-- Ketchup
-- Molho de pimenta
-- Salsicha
-- Linguiça
-- Peixe
-- Atum
-- Sardinha
-- Margarina
-- Manteiga
-- Iogurte
-- Geléia
-- Cereal
-- Granola
-- Aveia
-- Biscoitos
-- Bolacha
-- Chocolate
-- Achocolatado
-- Balas
-- Chiclete
-- Pipoca
-- Amendoim
-- Castanhas
-- Nozes
-- Pistache
-- Refrigerante
-- Cerveja
-- Vinho
-- Espumante
-- Vodka
-- Whisky
-- Tequila
-- Rum
-- Vermute
-- Martini
-- Campari
-- Aperol
-- Licor
-- Vermute
-- Azeitonas
-- Picles
-- Conservas
-- Frutas em calda
-- Geleia real
-- Mel
-- Nutella
-- Peanut butter
-- Marshmallows
-- Açúcar mascavo
-- Adoçante
-- Melado
-- Calda de chocolate
-- Calda de caramelo
-- Chantilly
-- Creme de avelã
-- Patê
-- Ricota
-- Requeijão
-- Creme de ricota
-- Creme de alho
-- Creme de cebola
