version: '3'

services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - backend
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    networks:
      - backend
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin

  django_service:
    container_name: django_service
    working_dir: /app
    build:
        context: .
        dockerfile: ./django_service.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_started

volumes:
    postgres:
    pgadmin:

networks:
  backend:
