services:
  django_service:
    working_dir: /app
    env_file: .env
    build: .
    ipc: "shareable"
    ports:
      - "8000:8000"
    entrypoint: "python3"
    command: manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
    postgres: