# Generated by Django 5.0.3 on 2024-04-02 18:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefaultCategorys",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "default_categorys",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        db_column="id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Nome"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Mercado",
                "verbose_name_plural": "Mercados",
                "db_table": "markets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingList",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        db_column="id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "final_value",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Sempre deve ser armazenado em formato inteiro!",
                        verbose_name="Valor final",
                    ),
                ),
                (
                    "unique_items",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Itens únicos"
                    ),
                ),
                (
                    "total_items",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Total de itens"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lista de compras",
                "verbose_name_plural": "Listas de compras",
                "db_table": "shopping_list",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnityTypes",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
                ("abbreviation", models.CharField(max_length=5, unique=True)),
                (
                    "factor",
                    models.PositiveSmallIntegerField(verbose_name="Base de calculo"),
                ),
            ],
            options={
                "verbose_name": "Tipo de unidade",
                "verbose_name_plural": "Tipos de unidades",
                "db_table": "unity_types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserCategorys",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        db_column="id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "user_categorys",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        db_column="id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(max_length=255, verbose_name="Nome"),
                ),
                (
                    "password",
                    models.CharField(max_length=255, verbose_name="Senha"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de aniversário",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "db_table": "users",
                "ordering": ["nickname"],
            },
        ),
        migrations.CreateModel(
            name="DefaultProducts",
            fields=[
                (
                    "_id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="Image URL"),
                ),
                (
                    "default_categorys_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_de_compras.defaultcategorys",
                    ),
                ),
                (
                    "unity_types_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_de_compras.unitytypes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "default_products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProducts",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        db_column="id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "price",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Sempre deve ser armazenado em formato inteiro!",
                        verbose_name="Preço",
                    ),
                ),
                (
                    "notes",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "barcode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="Image URL"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_de_compras.usercategorys",
                    ),
                ),
                (
                    "price_unity_types_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_unity_types_id",
                        to="lista_de_compras.unitytypes",
                    ),
                ),
                (
                    "unity_types_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_de_compras.unitytypes",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_de_compras.users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "user_products",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductList",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        db_column="id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Quantidade"
                    ),
                ),
                (
                    "price",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Sempre deve ser armazenado em formato inteiro!",
                        verbose_name="Preço",
                    ),
                ),
                (
                    "total",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Sempre deve ser armazenado em formato inteiro!",
                        verbose_name="Total",
                    ),
                ),
                (
                    "on_cart",
                    models.BooleanField(default=False, verbose_name="No carrinho"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shopping_list_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_de_compras.shoppinglist",
                    ),
                ),
                (
                    "user_product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_de_compras.userproducts",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da lista",
                "verbose_name_plural": "Itens da lista",
                "db_table": "product_list",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="usercategorys",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lista_de_compras.users",
            ),
        ),
        migrations.CreateModel(
            name="ShoppingLog",
            fields=[
                (
                    "_id",
                    models.UUIDField(
                        db_column="id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "buy_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da compra"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "market_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_de_compras.market",
                    ),
                ),
                (
                    "shopping_list_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_de_compras.shoppinglist",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lista_de_compras.users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de compras",
                "verbose_name_plural": "Logs de compras",
                "db_table": "shopping_log",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="shoppinglist",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lista_de_compras.users",
            ),
        ),
        migrations.AddField(
            model_name="market",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="lista_de_compras.users",
            ),
        ),
    ]
