# Generated by Django 5.0.4 on 2024-04-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_de_compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategorys',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userproducts',
            unique_together=set(),
        ),
    ]
