# Generated by Django 5.0.4 on 2024-04-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista_de_compras', '0002_alter_usercategorys_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercategorys',
            unique_together={('name', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userproducts',
            unique_together={('name', 'user_id')},
        ),
    ]
