# Generated by Django 5.0.4 on 2024-04-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_de_compras', '0003_alter_usercategorys_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproducts',
            name='price',
            field=models.FloatField(default=0, help_text='Sempre deve ser armazenado em formato inteiro!', verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Usuário ativo'),
        ),
    ]
