# Generated by Django 5.0.4 on 2024-04-18 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista_de_compras', '0004_alter_userproducts_price_alter_users_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='user_id',
            field=models.ForeignKey(db_column='user_id+', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user_id',
            field=models.ForeignKey(db_column='user_id+', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shoppinglog',
            name='user_id',
            field=models.ForeignKey(db_column='user_id+', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercategorys',
            name='user_id',
            field=models.ForeignKey(db_column='user_id+', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userproducts',
            name='user_id',
            field=models.ForeignKey(db_column='user_id+', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
